transaction_product_list:
    path:     /product_list
    defaults: { _controller: TransactionBundle:Default:productList }

transaction_pos:
    path: /pos
    defaults: { _controller: TransactionBundle:Default:pos }
    
transaction_pos2:
    path: /pos2
    defaults: { _controller: TransactionBundle:Default:pos2 }
    
sale_transaction:
    type: rest
    resource: "TransactionBundle:Api"
    prefix: api
    
sale_transaction2:
    path: /sale
    defaults: { _controller: TransactionBundle:Default:sale }