transaction_pos2:
    path: /pos2
    defaults: { _controller: TransactionBundle:Default:pos2 }
    
transaction_pos_barcode:
    path: /pos_barcode
    defaults: { _controller: TransactionBundle:Default:pos }
    
sale_transaction:
    type: rest
    resource: "TransactionBundle:Api"
    prefix: api