km_synchronizer:
    path:  /synchronizer
    defaults: { _controller: KmBundle:Default:synchronizer }
    
km_front:
    path:    /
    defaults: { _controller: KmBundle:Default:front }
    
km_validate_update_stock:
    path: /validate_update_stock/{update}
    defaults: { _controller: KmBundle:Default:validateUpdateStock }
    
sales: 
  type: rest
  resource:     "TransactionBundle:Api"
  prefix:  api
  
km_homepage:
    path: /generate_barcode/{barcode}
    defaults: { _controller: KmBundle:Default:index }