km_homepage:
    path:     /generate_barcode
    defaults: { _controller: KmBundle:Default:index }
    
km_dashboard:
    path:    /report
    defaults: { _controller: KmBundle:Default:dashboard }
    
km_documentation:
    path:    /
    defaults: { _controller: KmBundle:Default:front }
