services:
    km.barcode_handler:
        class: KmBundle\Service\BarcodeHandler
        arguments: ["@doctrine.orm.entity_manager"]
        
    km.stock_handler:
        class: KmBundle\Service\StockHandler
        arguments: ["@doctrine.orm.entity_manager"]
        
    km.notification_handler:
        class: KmBundle\Service\NotificationHandler
        arguments: ["@doctrine.orm.entity_manager"]

    km.synchronizer_handler:
            class: KmBundle\Service\SynchronizerHandler
            arguments: ["@guzzle.client.api_crm", "@doctrine.orm.entity_manager"]
        
    km.report_handler:
        class: KmBundle\Service\ReportHandler
        arguments: ["@doctrine.orm.entity_manager"]
        
    km.statistic_handler:
        class: KmBundle\Service\StatisticHandler
        arguments: ["@doctrine.orm.entity_manager"]

    km.admin.expenditure:
        class: KmBundle\Admin\ExpenditureAdmin
        arguments: [~, KmBundle\Entity\Expenditure, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Expenditure }

    km.admin.branch:
        class: KmBundle\Admin\BranchAdmin
        arguments: [~, KmBundle\Entity\Branch, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Branch }
    
    km.api_handler:
        class: KmBundle\Service\ApiHandler
        arguments: ["@doctrine.orm.entity_manager", "@security.encoder_factory", "@fos_user.user_provider.username", "@security.token_storage", "@service_container"]
