services:
    
    km.stock_handler:
        class: KmBundle\Service\StockHandler
        arguments: ["@doctrine.orm.entity_manager"]
        
    km.statisticHandler:
        class: KmBundle\Service\StatisticHandler
        arguments: ["@doctrine.orm.entity_manager"]

    km.admin.expenditure:
        class: KmBundle\Admin\ExpenditureAdmin
        arguments: [~, KmBundle\Entity\Expenditure, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Expenditure }

    km.admin.branch:
        class: KmBundle\Admin\BranchAdmin
        arguments: [~, KmBundle\Entity\Branch, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Branch }
